spring.application.name=restapi
spring.datasource.url=jdbc:postgresql://ep-noisy-poetry-ap3iy971-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_h0QEXc5CeniP

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true